name: Desde Gomeslavia con amor
description: Tribulaciones, cábalas y demás pensamientos sin orden ni concierto.

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ''
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://himliano.github.io"
author: "Himliano"

# Disqus config
disqus-shortname: "desde-gomeslavia-con-amor"
