# Setup
title:               'Desde Gomeslavia con amor'
description:         'Tribulaciones, cábalas y demás pensamientos sin orden ni concierto con el único afán de sacarlos de mi cabeza y hacer sitio para muchos otros nuevos.'
url:                 https://himliano.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

version: 0.1

# About/contact
author:
  name:              Himliano

# Gems
plugins:
  - jekyll-paginate
